config/routes.rb
Rainforest::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "user/new"
  get "user/create"
  resources :products
  resources :users, :only =>[:new, :create]
  resources :sessions, :only =>[:new, :create, :destroy]

  resources :products do
    resources :reviews, :except => [:index]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :name, :description, :presence => true
 	validates :price_in_cents, { :numericality => {:only_integer => true} }

 	has_many :reviews
 	has_many :users, :through => :reviews

 	def formatted_price
 		price_in_dollars = price_in_cents.to_f / 100
 		sprintf("%.2f", price_in_dollars)
 	end

end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reviews
	has_many :products, :through => :reviews

	validates :name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	return @current_user = @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  	helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please login"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only =>[:show]

  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])

    if current_user
     @review = @product.reviews.build #build generates a new review to be associated
    end

  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params())
  	if @product.save
  		redirect_to products_path
  	else
  		render :new
  	end
  end

  def update
  	@product = Product.find(params[:id])
  	if @product.update_attributes(product_params())
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
  end


  private

  def product_params
  	params().require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]
	before_filter :load_product


  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user_id = current_user.id

    if @review.save
      redirect_to products_path, notice: 'Review added!'
    else
      render :action => :show
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

  end

  private

  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_path, :notice => "Logged in!"
  	else
  		flash[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_path :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url :notice => "User signed up!"
  	else
  		render "new"
  	end
  end


  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


	def clear
		raw('<div class="clear"></div>')
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice]  %>
		<p> <id = "notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert]  %>
		<p> <id = "alert"><%= flash[:alert] %></p>
	<% end %>

<%= yield %>
	<%= clear %>
	<p>
	<% if current_user %>
		Signed in as <%= current_user.name%>. <%= link_to("Log out", session_path("current"), :method => :delete) %>
	<!-- the :method => :delete above refers to the HTTP request delete, NOT THE controller action destroy-->
	<% else %>
		<%= link_to("Login", new_session_path) %> <%= link_to("Sign up", new_user_path) %>
	<% end %>
	</p>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<% if @product.errors.any?  %>
		<div>
		<h2><%= pluralize(@product.errors.count, "error") %> caused this product to fail!</h2>

		<ul>
			<% @product.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
		</div>
	<% end  %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :price_in_cents %>
		<%= f.number_field :price_in_cents %>
	</p>
	<p>
		<%= f.submit "Save" %>
	</p>
<% end  %>

app/views/products/_product_info.erb
<div class="left">
<strong>Product </strong>
<% @products.each do |product| %>
	<li><%= link_to product.name, product_path(product) %></li>
<% end %>
</div>

<div class="left">
<strong>Description </strong>
<% @products.each do |product| %>
	<li><%=  product.description %></li>
<% end %>
</div>

<div class="left">
<strong>Price </strong>
<% @products.each do |product| %>
	<li>$<%=  product.formatted_price %></li>
<% end %>
</div>


<div class="left">
<strong>Actions </strong>
<% @products.each do |product| %>
			<li><%= link_to("Edit", edit_product_path(product))%>  <%= link_to("Delete", product_path(product), :method => :delete) %></li>
	<% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit the Product </h1>
<%= link_to("All Products", products_path) %>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>All Products</h1>
<%= link_to("Add New Product", new_product_path) %><br />


<p>
	<%= render "product_info" %>
</p>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= link_to("All Products", products_path) %>
<%= render 'form' %>

app/views/products/show.html.erb
<% if current_user  %>
	<h3>Reviews</h3>

	<p>Reviews for <%= @product.name %></p>

		<% counter = 1 %>

	<% @product.reviews.each do |review| %>
		<% unless review.new_record? %>
		<p>
		<%= counter %>) <%= review.comment %>
		<% if review.user != nil %>
			This review was written by <%= review.user.name %><br>
			on <%= review.created_at %>
		<% end %>
			<% counter = counter + 1  %>

		</p>
		<% end %>
	<% end  %>

	<h4>New Review</h4>


<%= form_for([@product, @review]) do |f| %>

		<% if @review.errors.any?  %>
			<h2><%= pluralize(@review.errors.count, "error") %> prevented this from being saved </h2>

			<ul>
			<% @review.errors.full_messages.each do |error|  %>
				<li> <%= error %> </li>
				<% end  %>
			</ul>
		<% end %>

		 <div>
		 	<%= f.label :comment %><br />
		 	<%= f.text_area :comment %>
		 </div>
		 <div>
		 	<%= f.submit %>
		 </div>
	<% end %>

<% else  %>

	Please <%= link_to("login", new_session_path) %> to add a new review



<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
	<% if @user.errors.any?  %>

		<h2>Form is invalid because of the following:</h2>
		<ul>
		<% @user.errors.each do |message| %>

			<li><%= message %></li>
		<% end %>
		</ul>
	<% end %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>

	<%= f.label :email %>
	<%= f.text_field :email %>
	<br>

	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br>

	<%= f.submit "Submit" %>


<% end %>